name: lint

on:
  workflow_call:

jobs:
  lint:
    name: Check Cargo fmt linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get Stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt

    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.event.repository.default_branch == github.ref_name }}

    - name: Run rustfmt
      run: cargo fmt --check