name: build

on:
  push:
    tags:
      - 'v\d+\.\d+\.\d+'

jobs:
  update-changelog:
    name: Update Changelog
    uses: ./.github/workflows/changelog.yml
    with:
      branch: 'main'
    secrets: inherit

  build:
    name: Build and Test
    needs: update-changelog
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Install Dependencies
      run: cargo fetch

    - name: Build
      run: cargo build --release

    - name: Run Tests
      run: cargo test

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.CHANGELOG_APP_ID }}
        private-key: ${{ secrets.CHANGELOG_APP_KEY }}

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}
    
    - name: Generate changelog
      uses: orhun/git-cliff-action@v3
      id: git-cliff
      with:
        config: cliff.toml
        args: -vv --latest --strip header
      env:
        OUTPUT: CHANGES.md

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.git-cliff.outputs.content }}
        draft: false
        prerelease: false